#this pipeline will be trigger to run by master branch of github repo. 
trigger:
 - master
#add variables
variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
