#this pipeline will be trigger to run by master branch of github repo. 
trigger:
 - master
pool:
  name: kdacpool
  demands:
   - agent.name -equals opensource11
#add variables
variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - task: Docker@2
       inputs:
        containerRegistry: 'kdac-test'
        repository: 'kdacacr'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'